Enc.register('sources', {
  "sources": {
    "bukhari": { "ar": "صحيح البخاري", "short_ar": "البخاري", "en": "Sahih al-Bukhari", "short_en": "al-Bukhari", "kind": "hadith", "sahih": true, "url": "https://sunnah.com/bukhari:{n}" },
    "muslim": { "ar": "صحيح مسلم", "short_ar": "مسلم", "en": "Sahih Muslim", "short_en": "Muslim", "kind": "hadith", "sahih": true },
    "abudawud": { "ar": "سنن أبي داود", "short_ar": "أبو داود", "en": "Sunan Abi Dawud", "short_en": "Abu Dawud", "kind": "hadith", "url": "https://sunnah.com/abudawud:{n}" },
    "tirmidhi": { "ar": "جامع الترمذي", "short_ar": "الترمذي", "en": "Jami' al-Tirmidhi", "short_en": "al-Tirmidhi", "kind": "hadith", "url": "https://sunnah.com/tirmidhi:{n}" },
    "ahmad": { "ar": "مسند الإمام أحمد (طبعة الرسالة)", "short_ar": "مسند أحمد", "en": "Musnad Ahmad (al-Risalah edition)", "short_en": "Ahmad", "kind": "hadith" },
    "nasai": { "ar": "سنن النسائي", "short_ar": "النسائي", "en": "Sunan al-Nasa'i", "short_en": "al-Nasa'i", "kind": "hadith" },
    "ibnmajah": { "ar": "سنن ابن ماجه", "short_ar": "ابن ماجه", "en": "Sunan Ibn Majah", "short_en": "Ibn Majah", "kind": "hadith", "url": "https://sunnah.com/ibnmajah:{n}" },
    "umari": { "ar": "السيرة النبوية الصحيحة — أكرم ضياء العمري", "short_ar": "السيرة النبوية الصحيحة", "en": "al-Sirah al-Nabawiyyah al-Sahihah — Akram Diya al-Umari", "short_en": "al-Umari", "kind": "sirah" },
    "siyar": { "ar": "سير أعلام النبلاء — الذهبي", "short_ar": "سير أعلام النبلاء", "en": "Siyar A'lam al-Nubala' — al-Dhahabi", "short_en": "Siyar A'lam al-Nubala'", "kind": "sirah" },
    "zad": { "ar": "زاد المعاد — ابن القيم", "short_ar": "زاد المعاد", "en": "Zad al-Ma'ad — Ibn al-Qayyim", "short_en": "Zad al-Ma'ad", "kind": "sirah" },
    "uthaymeen-riyad": { "ar": "شرح رياض الصالحين — ابن عثيمين", "short_ar": "شرح رياض الصالحين", "en": "Sharh Riyad al-Salihin — Ibn Uthaymeen", "short_en": "Sharh Riyad al-Salihin", "kind": "sharh" },
    "bajuri-shamail": { "ar": "المواهب اللدنية على الشمائل المحمدية — الباجوري", "short_ar": "شرح الباجوري على الشمائل", "en": "al-Mawahib al-Ladunniyyah on al-Shama'il — al-Bajuri", "short_en": "al-Bajuri", "kind": "sharh" },
    "fath": { "ar": "فتح الباري شرح صحيح البخاري — ابن حجر العسقلاني (ط. السلفية)", "short_ar": "فتح الباري", "en": "Fath al-Bari, commentary on Sahih al-Bukhari — Ibn Hajar al-'Asqalani (Salafiyyah ed.)", "short_en": "Fath al-Bari", "kind": "sharh" },
    "nawawi": { "ar": "المنهاج شرح صحيح مسلم — النووي", "short_ar": "شرح النووي على مسلم", "en": "al-Minhaj, commentary on Sahih Muslim — al-Nawawi", "short_en": "al-Nawawi's commentary", "kind": "sharh" },
    "ibnkathir": { "ar": "تفسير القرآن العظيم — ابن كثير", "short_ar": "تفسير ابن كثير", "en": "Tafsir al-Qur'an al-'Azim — Ibn Kathir", "short_en": "Tafsir Ibn Kathir", "kind": "sharh" },
    "tarikh": { "ar": "التاريخ الكبير — البخاري (ترجمة عقيل بن أبي طالب)", "short_ar": "التاريخ الكبير", "en": "al-Tarikh al-Kabir — al-Bukhari (entry: 'Aqil ibn Abi Talib)", "short_en": "al-Tarikh al-Kabir", "kind": "book" },
    "yaqut": { "ar": "معجم البلدان — ياقوت الحموي", "short_ar": "معجم البلدان", "en": "Mu'jam al-Buldan — Yaqut al-Hamawi", "short_en": "Mu'jam al-Buldan", "kind": "book" },
    "shifa": { "ar": "الشفا بتعريف حقوق المصطفى — القاضي عياض (مع حاشية الشمني)", "short_ar": "الشفا", "en": "Al-Shifa bi-Ta'rif Huquq al-Mustafa — al-Qadi 'Iyad (with al-Shumunni's notes)", "short_en": "al-Shifa", "kind": "book" },
    "alali": { "ar": "صحيح السيرة النبوية — إبراهيم العلي", "short_ar": "صحيح السيرة النبوية", "en": "Sahih al-Sirah al-Nabawiyyah — Ibrahim al-Ali", "short_en": "Sahih al-Sirah (al-Ali)", "kind": "sirah" },
    "quran": { "ar": "القرآن الكريم", "short_ar": "القرآن", "en": "The Noble Qur'an", "short_en": "Qur'an", "kind": "quran", "url": "https://quran.com/{n}",
      "surahs": [
        ["الفاتحة","al-Fatihah",7],
        ["البقرة","al-Baqarah",286],
        ["آل عمران","Al 'Imran",200],
        ["النساء","al-Nisa'",176],
        ["المائدة","al-Ma'idah",120],
        ["الأنعام","al-An'am",165],
        ["الأعراف","al-A'raf",206],
        ["الأنفال","al-Anfal",75],
        ["التوبة","al-Tawbah",129],
        ["يونس","Yunus",109],
        ["هود","Hud",123],
        ["يوسف","Yusuf",111],
        ["الرعد","al-Ra'd",43],
        ["إبراهيم","Ibrahim",52],
        ["الحجر","al-Hijr",99],
        ["النحل","al-Nahl",128],
        ["الإسراء","al-Isra'",111],
        ["الكهف","al-Kahf",110],
        ["مريم","Maryam",98],
        ["طه","Ta Ha",135],
        ["الأنبياء","al-Anbiya'",112],
        ["الحج","al-Hajj",78],
        ["المؤمنون","al-Mu'minun",118],
        ["النور","al-Nur",64],
        ["الفرقان","al-Furqan",77],
        ["الشعراء","al-Shu'ara'",227],
        ["النمل","al-Naml",93],
        ["القصص","al-Qasas",88],
        ["العنكبوت","al-'Ankabut",69],
        ["الروم","al-Rum",60],
        ["لقمان","Luqman",34],
        ["السجدة","al-Sajdah",30],
        ["الأحزاب","al-Ahzab",73],
        ["سبأ","Saba'",54],
        ["فاطر","Fatir",45],
        ["يس","Ya Sin",83],
        ["الصافات","al-Saffat",182],
        ["ص","Sad",88],
        ["الزمر","al-Zumar",75],
        ["غافر","Ghafir",85],
        ["فصلت","Fussilat",54],
        ["الشورى","al-Shura",53],
        ["الزخرف","al-Zukhruf",89],
        ["الدخان","al-Dukhan",59],
        ["الجاثية","al-Jathiyah",37],
        ["الأحقاف","al-Ahqaf",35],
        ["محمد","Muhammad",38],
        ["الفتح","al-Fath",29],
        ["الحجرات","al-Hujurat",18],
        ["ق","Qaf",45],
        ["الذاريات","al-Dhariyat",60],
        ["الطور","al-Tur",49],
        ["النجم","al-Najm",62],
        ["القمر","al-Qamar",55],
        ["الرحمن","al-Rahman",78],
        ["الواقعة","al-Waqi'ah",96],
        ["الحديد","al-Hadid",29],
        ["المجادلة","al-Mujadilah",22],
        ["الحشر","al-Hashr",24],
        ["الممتحنة","al-Mumtahanah",13],
        ["الصف","al-Saff",14],
        ["الجمعة","al-Jumu'ah",11],
        ["المنافقون","al-Munafiqun",11],
        ["التغابن","al-Taghabun",18],
        ["الطلاق","al-Talaq",12],
        ["التحريم","al-Tahrim",12],
        ["الملك","al-Mulk",30],
        ["القلم","al-Qalam",52],
        ["الحاقة","al-Haqqah",52],
        ["المعارج","al-Ma'arij",44],
        ["نوح","Nuh",28],
        ["الجن","al-Jinn",28],
        ["المزمل","al-Muzzammil",20],
        ["المدثر","al-Muddaththir",56],
        ["القيامة","al-Qiyamah",40],
        ["الإنسان","al-Insan",31],
        ["المرسلات","al-Mursalat",50],
        ["النبأ","al-Naba'",40],
        ["النازعات","al-Nazi'at",46],
        ["عبس","Abasa",42],
        ["التكوير","al-Takwir",29],
        ["الانفطار","al-Infitar",19],
        ["المطففين","al-Mutaffifin",36],
        ["الانشقاق","al-Inshiqaq",25],
        ["البروج","al-Buruj",22],
        ["الطارق","al-Tariq",17],
        ["الأعلى","al-A'la",19],
        ["الغاشية","al-Ghashiyah",26],
        ["الفجر","al-Fajr",30],
        ["البلد","al-Balad",20],
        ["الشمس","al-Shams",15],
        ["الليل","al-Layl",21],
        ["الضحى","al-Duha",11],
        ["الشرح","al-Sharh",8],
        ["التين","al-Tin",8],
        ["العلق","al-'Alaq",19],
        ["القدر","al-Qadr",5],
        ["البينة","al-Bayyinah",8],
        ["الزلزلة","al-Zalzalah",8],
        ["العاديات","al-'Adiyat",11],
        ["القارعة","al-Qari'ah",11],
        ["التكاثر","al-Takathur",8],
        ["العصر","al-'Asr",3],
        ["الهمزة","al-Humazah",9],
        ["الفيل","al-Fil",5],
        ["قريش","Quraysh",4],
        ["الماعون","al-Ma'un",7],
        ["الكوثر","al-Kawthar",3],
        ["الكافرون","al-Kafirun",6],
        ["النصر","al-Nasr",3],
        ["المسد","al-Masad",5],
        ["الإخلاص","al-Ikhlas",4],
        ["الفلق","al-Falaq",5],
        ["الناس","al-Nas",6]
      ] },
    "sahiha": { "ar": "السلسلة الصحيحة — الألباني", "short_ar": "الصحيحة", "en": "al-Silsilah al-Sahihah — al-Albani", "short_en": "al-Sahihah", "kind": "hadith" },
    "albani": { "ar": "الشيخ الألباني", "short_ar": "الألباني", "en": "Shaykh al-Albani", "short_en": "al-Albani", "kind": "grader" },
    "arnaut": { "ar": "الشيخ شعيب الأرناؤوط ومن معه (تحقيق المسند)", "short_ar": "الأرناؤوط", "en": "Shaykh Shu'ayb al-Arna'ut et al. (Musnad edition)", "short_en": "al-Arna'ut", "kind": "grader" }
  },
  "grades": {
    "sahih": { "ar": "صحيح", "en": "Sahih", "tier": 1 },
    "hasan": { "ar": "حسن", "en": "Hasan", "tier": 1 },
    "sirah": { "ar": "سيرة", "en": "Seerah report", "tier": 2 },
    "weak": { "ar": "ضعيف", "en": "Weak", "tier": 3 },
    "mursal": { "ar": "مرسل", "en": "Mursal", "tier": 3 },
    "fabricated": { "ar": "موضوع", "en": "Fabricated", "tier": 3 }
  }
});
